trigger:
- main  # Change this if using a different branch

pool:
  name: 'Default'  # Uses your self-hosted agent

steps:
- script: |
    set LT_USERNAME=anshulr
    set LT_ACCESS_KEY=LT_Vafdmse65NnAXvVWbRuR6d0Z9Qj7xq1e9AUI2qpbgK8vamb
    cd ios-sample
    npm install
  displayName: 'Set Env Variables & Install Dependencies'

- script: |
    set LT_USERNAME=anshulr
    set LT_ACCESS_KEY=LT_Vafdmse65NnAXvVWbRuR6d0Z9Qj7xq1e9AUI2qpbgK8vamb
    cd ios-sample
    npm run SingleiOSWeb
  displayName: 'Run Single iOS Web Tests'
